version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/fuzz"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
